#pragma once

typedef enum CastlingRights {
    CASTLING_RIGHTS_NONE,
    CASTLING_RIGHTS_WHITE_KINGSIDE,
    CASTLING_RIGHTS_WHITE_QUEENSIDE,
    CASTLING_RIGHTS_BLACK_KINGSIDE = 4,
    CASTLING_RIGHTS_BLACK_QUEENSIDE = 8,
} CastlingRights_t;
